//Error actions
export const READ_ERROR = 'READ_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

//Auth actions
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

//Process actions
export const LOADING_PROCESS = 'LOADING_PROCESS'
export const CREATE_PROCESS = 'CREATE_PROCESS'
export const READ_PROCESS = 'READ_PROCESS'
export const UPDATE_PROCESS = 'UPDATE_PROCESS'
export const DELETE_PROCESS = 'DELETE_PROCESS'
export const LIST_PROCESS = 'LIST_PROCESS'
export const GET_PROCESS_FILTERS = 'GET_PROCESS_FILTERS'

//Course actions
export const LOADING_COURSE = 'LOADING_COURSE'
export const CREATE_COURSE = 'CREATE_COURSE'
export const READ_COURSE = 'READ_COURSE'
export const UPDATE_COURSE = 'UPDATE_COURSE'
export const DELETE_COURSE = 'DELETE_COURSE'
export const LIST_COURSE = 'LIST_COURSE'

//GraduationLevel actions
export const LOADING_GRADUATIONLEVEL = 'LOADING_GRADUATIONLEVEL'
export const CREATE_GRADUATIONLEVEL = 'CREATE_GRADUATIONLEVEL'
export const READ_GRADUATIONLEVEL = 'READ_GRADUATIONLEVEL'
export const UPDATE_GRADUATIONLEVEL = 'UPDATE_GRADUATIONLEVEL'
export const DELETE_GRADUATIONLEVEL = 'DELETE_GRADUATIONLEVEL'
export const LIST_GRADUATIONLEVEL = 'LIST_GRADUATIONLEVEL'
