//Error actions
export const READ_ERROR = 'READ_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

//Auth actions
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

//Process actions
export const LOADING_PROCESS = 'LOADING_PROCESS'
export const CREATE_PROCESS = 'CREATE_PROCESS'
export const READ_PROCESS = 'READ_PROCESS'
export const UPDATE_PROCESS = 'UPDATE_PROCESS'
export const DELETE_PROCESS = 'DELETE_PROCESS'
export const LIST_PROCESS = 'LIST_PROCESS'
export const GET_PROCESS_FILTERS = 'GET_PROCESS_FILTERS'

//Course actions
export const LOADING_COURSE = 'LOADING_COURSE'
export const CREATE_COURSE = 'CREATE_COURSE'
export const READ_COURSE = 'READ_COURSE'
export const UPDATE_COURSE = 'UPDATE_COURSE'
export const DELETE_COURSE = 'DELETE_COURSE'
export const LIST_COURSE = 'LIST_COURSE'

//GraduationLevel actions
export const LOADING_GRADUATIONLEVEL = 'LOADING_GRADUATIONLEVEL'
export const CREATE_GRADUATIONLEVEL = 'CREATE_GRADUATIONLEVEL'
export const READ_GRADUATIONLEVEL = 'READ_GRADUATIONLEVEL'
export const UPDATE_GRADUATIONLEVEL = 'UPDATE_GRADUATIONLEVEL'
export const DELETE_GRADUATIONLEVEL = 'DELETE_GRADUATIONLEVEL'
export const LIST_GRADUATIONLEVEL = 'LIST_GRADUATIONLEVEL'

//processAssigment actions
export const LOADING_PROCESSASSIGNMENT = 'LOADING_PROCESSASSIGNMENT'
export const CREATE_PROCESSASSIGNMENT = 'CREATE_PROCESSASSIGNMENT'
export const READ_PROCESSASSIGNMENT = 'READ_PROCESSASSIGNMENT'
export const UPDATE_PROCESSASSIGNMENT = 'UPDATE_PROCESSASSIGNMENT'
export const DELETE_PROCESSASSIGNMENT = 'DELETE_PROCESSASSIGNMENT'
export const LIST_ADD_PROCESSASSIGNMENT = 'LIST_ADD_PROCESSASSIGNMENT'

//Assignment actions
export const LOADING_ASSIGNMENT = 'LOADING_ASSIGNMENT'
export const CREATE_ASSIGNMENT = 'CREATE_ASSIGNMENT'
export const READ_ASSIGNMENT = 'READ_ASSIGNMENT'
export const UPDATE_ASSIGNMENT = 'UPDATE_ASSIGNMENT'
export const DELETE_ASSIGNMENT = 'DELETE_ASSIGNMENT'
export const LIST_ASSIGNMENT = 'LIST_ASSIGNMENT'
